In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error, r2_score
from sklearn.model_selection import train_test_split

In [41]:
data=pd.read_csv('Salary_data.csv')
data.head()

Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0   
1  28.0  Female        Master's       Data Analyst                  3.0   
2  45.0    Male             PhD     Senior Manager                 15.0   
3  36.0  Female      Bachelor's    Sales Associate                  7.0   
4  52.0    Male        Master's           Director                 20.0   

     Salary  
0   90000.0  
1   65000.0  
2  150000.0  
3   60000.0  
4  200000.0

In [42]:
df=data[['Age','Salary']]
df.head()

Age    Salary
0  32.0   90000.0
1  28.0   65000.0
2  45.0  150000.0
3  36.0   60000.0
4  52.0  200000.0

In [43]:
data.isnull().sum()

Age                    2
Gender                 2
Education Level        3
Job Title              2
Years of Experience    3
Salary                 5
dtype: int64

In [44]:
data.dropna(inplace=True)

In [11]:
data.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [13]:
df=data.sample(1000)
df.head()

Age  Gender  Education Level                  Job Title  \
1374  54.0    Male              PhD  Software Engineer Manager   
2523  39.0    Male  Master's Degree  Software Engineer Manager   
5913  36.0  Female              PhD         Research Scientist   
4040  35.0  Female  Master's Degree          Marketing Manager   
3982  44.0    Male              PhD             Data Scientist   

      Years of Experience    Salary  
1374                 17.0  195000.0  
2523                 14.0  142360.0  
5913                 12.0  170000.0  
4040                 10.0  110000.0  
3982                 15.0  150000.0

In [14]:
x=df[['Age']]
y=df.Salary

In [16]:
from sklearn.linear_model import LinearRegression

In [20]:
linear_model = LinearRegression ()
linear_model.fit(x,y)

LinearRegression()

In [21]:
linear_model.intercept_

-57063.23997856969

In [22]:
linear_model.coef_

array([5184.17241937])

In [23]:
agenw=45
linear_model.predict([[agenw]])

C:\Users\Admin\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([176224.51889286])

In [24]:
#Mean Squared Error

In [25]:
ypred=linear_model.predict(x)

In [26]:
x.head()

Age
1374  54.0
2523  39.0
5913  36.0
4040  35.0
3982  44.0

In [27]:
y

1374    195000.0
2523    142360.0
5913    170000.0
4040    110000.0
3982    150000.0
          ...   
4279    119000.0
6111     60000.0
6195    170000.0
2386    101332.0
2452    134858.0
Name: Salary, Length: 1000, dtype: float64

In [28]:
ypred

array([222882.07066715, 145119.48437667, 129566.96711858, 124382.79469921,
       171040.3464735 ,  67356.89808619,  82909.41534429,  62172.72566683,
        93277.76018302, 108830.27744112,  93277.76018302,  62172.72566683,
        82909.41534429, 191777.03615096, 103646.10502175, 139935.31195731,
       181408.69131223, 176224.51889286, 171040.3464735 , 171040.3464735 ,
       108830.27744112,  88093.58776366, 103646.10502175, 155487.8292154 ,
        93277.76018302, 176224.51889286,  82909.41534429,  82909.41534429,
        88093.58776366,  67356.89808619,  67356.89808619,  82909.41534429,
       103646.10502175,  88093.58776366, 222882.07066715, 139935.31195731,
        88093.58776366, 145119.48437667, 145119.48437667, 108830.27744112,
       171040.3464735 , 108830.27744112,  88093.58776366,  72541.07050556,
        82909.41534429, 114014.44986048,  88093.58776366, 160672.00163477,
       114014.44986048,  77725.24292492, 108830.27744112, 114014.44986048,
       160672.00163477,  

In [29]:
error=y-ypred
ypred

array([222882.07066715, 145119.48437667, 129566.96711858, 124382.79469921,
       171040.3464735 ,  67356.89808619,  82909.41534429,  62172.72566683,
        93277.76018302, 108830.27744112,  93277.76018302,  62172.72566683,
        82909.41534429, 191777.03615096, 103646.10502175, 139935.31195731,
       181408.69131223, 176224.51889286, 171040.3464735 , 171040.3464735 ,
       108830.27744112,  88093.58776366, 103646.10502175, 155487.8292154 ,
        93277.76018302, 176224.51889286,  82909.41534429,  82909.41534429,
        88093.58776366,  67356.89808619,  67356.89808619,  82909.41534429,
       103646.10502175,  88093.58776366, 222882.07066715, 139935.31195731,
        88093.58776366, 145119.48437667, 145119.48437667, 108830.27744112,
       171040.3464735 , 108830.27744112,  88093.58776366,  72541.07050556,
        82909.41534429, 114014.44986048,  88093.58776366, 160672.00163477,
       114014.44986048,  77725.24292492, 108830.27744112, 114014.44986048,
       160672.00163477,  

In [30]:
error2=np.power(error,2)
error2

1374    7.774099e+08
2523    7.614754e+06
5913    1.634830e+09
4040    2.068648e+08
3982    4.426962e+08
            ...     
4279    4.382873e+08
6111    1.572784e+08
6195    2.580780e+09
2386    5.313391e+08
2452    2.577910e+07
Name: Salary, Length: 1000, dtype: float64

In [31]:
mse=np.mean(error2)
print(f'MSE : {mse:.2f}')

MSE : 1246932345.55


In [32]:
#syntax : mean_squared_error(yactual,ypredicted)

In [ ]:
ypred

In [33]:
mse=mean_squared_error(y,ypred)
print(f'MSE : {mse:.2f}')

MSE : 1246932345.55


In [34]:
#Root_Mean_Squared_error
rmse=np.sqrt(mse)
print(f'RMSE : {rmse:.2f}')

RMSE : 35311.93


In [35]:
#Mean Absolute Error
mae=mean_absolute_error(y, ypred)
print(f'MAE : {mae:.2f}')

MAE : 28174.35


In [36]:
#Mean Absolute Percentage Error
mape=mean_absolute_percentage_error(y, ypred)
mape=mape*100
print(f'MAPE : {mape:.2f}%')

MAPE : 34.37%


In [37]:
# R2_score
r2=r2_score(y,ypred)
print(f'R2 - score : {r2:.2f}')

R2 - score : 0.54


Train

X-prediction : y ypred
Testing


In [ ]:
Testing-dont give the data of training

In [ ]:
Data
     -training data ("training data are greater than testing data")
     -testing data

In [ ]:
Data-
   x,y
  xtrain, xtest,          ytrain, ytest

In [45]:
#once again


In [46]:
data=pd.read_csv('Salary_data.csv')
data.head()

Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0   
1  28.0  Female        Master's       Data Analyst                  3.0   
2  45.0    Male             PhD     Senior Manager                 15.0   
3  36.0  Female      Bachelor's    Sales Associate                  7.0   
4  52.0    Male        Master's           Director                 20.0   

     Salary  
0   90000.0  
1   65000.0  
2  150000.0  
3   60000.0  
4  200000.0

In [47]:
data.isnull().sum()

Age                    2
Gender                 2
Education Level        3
Job Title              2
Years of Experience    3
Salary                 5
dtype: int64

In [49]:
data.dropna(inplace=True)

In [51]:
data.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [52]:
# Create x and y
x=data[['Age']]
y=data.Salary

In [53]:
x

Age
0     32.0
1     28.0
2     45.0
3     36.0
4     52.0
...    ...
6699  49.0
6700  32.0
6701  30.0
6702  46.0
6703  26.0

[6698 rows x 1 columns]

In [54]:
y

0        90000.0
1        65000.0
2       150000.0
3        60000.0
4       200000.0
          ...   
6699    200000.0
6700     50000.0
6701     55000.0
6702    140000.0
6703     35000.0
Name: Salary, Length: 6698, dtype: float64

In [56]:
xtrain

Age
2929  46.0
4258  27.0
374   44.0
1132  34.0
1779  48.0
...    ...
5704  26.0
2553  31.0
539   27.0
1222  42.0
4275  29.0

[5358 rows x 1 columns]

In [60]:
ytrain

2929    150729.0
4258     36000.0
374     150000.0
1132    195000.0
1779    185000.0
          ...   
5704     55000.0
2553    100052.0
539     140000.0
1222    180000.0
4275     71000.0
Name: Salary, Length: 5358, dtype: float64

In [63]:
model=LinearRegression()
model.fit(xtrain, ytrain)

LinearRegression()

In [ ]:
#Evaluation
xtest      ytest        ypredicition

In [64]:
yprediction=model.predict(xtest)

In [65]:
yprediction

array([ 96864.3975814 ,  91857.04807984, 136923.19359391, ...,
        76834.99957515,  96864.3975814 , 106879.09658453])

In [ ]:
xtest      ytest        ypredicition


In [69]:
mae=mean_absolute_error(ytest, yprediction)
print(f'MAE : {mae:.2f}')

MAE : 28870.10


In [ ]:
#assignment 
X=data[['Age', 'Years of Experience']]