In [2]:
print(6)

6


In [3]:
print(6)

6


In [ ]:
Run : CTRL +ENTER
    shift +Enter
Add cell : Esc +b
asterisk indicates running of code
empty stands indicate no excution of code
number indicate end of excution of code
# indicates heading 

## second heading(font small hunch)

In [5]:
### third heading 
#### fourth heading 



###### sixth heading


- A
- B


1. A
2. B


## Numpy

In [ ]:
Numerical Python 
Computing /statistical
homogeneous

In [10]:
abc=[5,6,7,8,'data']
print(abc)

[5, 6, 7, 8, 'data']


In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
pip install --upgrade pip

   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ---------------------- ----------------- 1.0/1.8 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 3.3 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 24.3.1
    Uninstalling pip-24.3.1:
      Successfully uninstalled pip-24.3.1
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [8]:
x=np.array([5,7,4,9,12])
print(x)

[ 5  7  4  9 12]


In [1]:
1. numpy indexing 
2. numpy slicing
Attributes
shape
size
ndim
type


SyntaxError: invalid syntax (965766793.py, line 1)

In [7]:
a=np.array([1,2,3,4,5,6,7,8])
print(a[: : 3])


[1 4 7]


In [8]:
print(a[ :5])

[1 2 3 4 5]


In [11]:
ar=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(ar[1: , 1:])

[[5 6]
 [8 9]]


In [13]:
print(ar[2: , : ])

[[7 8 9]]


In [14]:
print(ar[1,2])

6


In [15]:
print(ar[2,2])

9


In [16]:
print(a[4])

5


In [17]:
print(ar.ndim)

2


In [18]:
print(ar.shape)

(3, 3)


In [19]:
print(ar.size)

9


In [20]:
print(type(ar))

<class 'numpy.ndarray'>


In [21]:
print(a.size)

8


In [22]:
print(a.shape)

(8,)
