In [52]:
import numpy as np
x=np.array([5,4,6,1])
y=np.array([2,1,3,4])
z=x+2
print(z)

[7 6 8 3]


In [53]:
#Broadcasting
[5,4,6,1] + [2,2,2,2]

[5, 4, 6, 1, 2, 2, 2, 2]

In [54]:
#Reshaping
print(x.shape)


(4,)


In [55]:
x.reshape(2,2)

array([[5, 4],
       [6, 1]])

In [7]:
x=np.array([4,6,2,7,9,12]) # vector

In [8]:
print(x.shape)

(6,)


In [ ]:
(3,2)
(2,3)
(1,6)
(6,1)


In [10]:
x.reshape(3,2)

array([[ 4,  6],
       [ 2,  7],
       [ 9, 12]])

In [11]:
x.reshape(2,3)

array([[ 4,  6,  2],
       [ 7,  9, 12]])

In [13]:
print(x.reshape(1,6)) # row matrix

[[ 4  6  2  7  9 12]]


In [14]:
print(x.reshape(6,1)) # column matrix

[[ 4]
 [ 6]
 [ 2]
 [ 7]
 [ 9]
 [12]]


In [15]:
x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [25]:
x=np.array([5,6,2,7]) 
# to append elemnets at the last
print(np.append(x,9))
# to append elements at particular index
# syntax => np.insert(array_name, index,elemnets)
print(np.insert(x,1,9))
x[1]=9

[5 6 2 7 9]
[5 9 6 2 7]


In [28]:
x=np.zeros((2,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [29]:
x=np.zeros(10).reshape(2,5)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
x=np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [31]:
# np.full()
z=np.full(7,5)
print(z)

[5 5 5 5 5 5 5]


In [33]:
z=np.full((2,3),7)
print(z)

[[7 7 7]
 [7 7 7]]


In [37]:
# np.arrange
x=np.arange(2,10,2).reshape(2,2)   # syntax=> np.arange(start,stop,step) 
print(x)

[[2 4]
 [6 8]]


In [38]:
#np.linspace
x=np.linspace(1,10,5) # syntax => np.linspace(start,stop, no of elements)
print(x)


[ 1.    3.25  5.5   7.75 10.  ]


In [39]:
#np.linspace
x=np.linspace(1,10,15) # syntax => np.linspace(start,stop, no of elements)
print(x)


[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]


In [41]:
x=np.random.random(6)    #genraetes random number between 0 t0 1 
# syntax=> np.random.random(no_of_elements)
print(x)

[0.96755256 0.09722016 0.67702567 0.3861993  0.08023806 0.53006215]


In [43]:
x=np.random.random((5,2) )
print(x)

[[0.14402183 0.64852159]
 [0.52493757 0.98872516]
 [0.00460269 0.50968463]
 [0.89416489 0.04000989]
 [0.85984738 0.84457235]]


In [45]:
x=np.random.randint(0,10,5)   # synatx np.random.randint(start , stop_range , size=kati ota number chayo herney)
print(x)

[4 5 3 6 5]


In [46]:
x=np.random.randint(0,10,15)   # synatx np.random.randint(start , stop_range , size=kati ota number chayo herney)
print(x)

[2 7 2 4 2 6 8 3 6 1 2 2 7 1 1]


In [50]:
z=np.random.uniform(0,10,5) # syntax np.random.uniform(start_range, stop_range, size=kati ota number )
# it generates only float
print(z)

[2.48275144 1.974712   4.40989137 6.10985571 7.96694676]
