In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix


# KNN

In [ ]:
-DISTANCE  BASED
- VALUE OF K=5, NUMBER OF NEIGHBORS
- TOP  5 minimum distance

In [2]:
#Label Encoding

In [3]:
from sklearn.preprocessing import LabelEncoder

In [12]:
df=sns.load_dataset('iris')

In [13]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [14]:
#fir_transfrom()
encoder=LabelEncoder()
df['Label']=encoder.fit_transform(df.species)

In [15]:
df

sepal_length  sepal_width  petal_length  petal_width    species  Label
0             5.1          3.5           1.4          0.2     setosa      0
1             4.9          3.0           1.4          0.2     setosa      0
2             4.7          3.2           1.3          0.2     setosa      0
3             4.6          3.1           1.5          0.2     setosa      0
4             5.0          3.6           1.4          0.2     setosa      0
..            ...          ...           ...          ...        ...    ...
145           6.7          3.0           5.2          2.3  virginica      2
146           6.3          2.5           5.0          1.9  virginica      2
147           6.5          3.0           5.2          2.0  virginica      2
148           6.2          3.4           5.4          2.3  virginica      2
149           5.9          3.0           5.1          1.8  virginica      2

[150 rows x 6 columns]

In [16]:
encoder.classes_

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [18]:
df.Label.unique()

array([0, 1, 2])

In [ ]:
# it follow alphabhetical order

In [19]:
# Data Scaling

In [ ]:
Data ko range same same  banauney ntr auta feature le arkho lai dominant

In [ ]:
a) Min-MAx Scaling (Normalization)
=> xscaled= (x-xmin)/(xmax-xmin)
Range specially >(0,1)
for change the range 
=> 
xscaled= xrange_min + [(x-xmin)/(xmax-xmin)] * xrange_max
Range=> (xrange_min, xrange_max)

In [ ]:
b) Standardization (z-score Normalization)
=> (x-mean)/deviation
=>

In [20]:
data=pd.read_csv('Diabetes.csv')

In [21]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [51]:
x=data[['Glucose' ,'Age']]
y=data.Outcome

In [30]:
# data scaling
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [31]:
#Note : Scaling is done after train_test_split

In [32]:
xtrain, xtest, ytrain, ytest=train_test_split(x,y ,test_size=0.2, random_state=9)

In [33]:
#Standard Scaler

In [36]:
scaler=StandardScaler()
data['BloodPressure']=scaler.fit_transform(data[['BloodPressure']])

In [37]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148       0.149641             35        0  33.6   
1            1       85      -0.160546             29        0  26.6   
2            8      183      -0.263941              0        0  23.3   
3            1       89      -0.160546             23       94  28.1   
4            0      137      -1.504687             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [39]:
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000   7.680000e+02     768.000000  768.000000   
mean      3.845052  120.894531   1.503427e-17      20.536458   79.799479   
std       3.369578   31.972618   1.000652e+00      15.952218  115.244002   
min       0.000000    0.000000  -3.572597e+00       0.000000    0.000000   
25%       1.000000   99.000000  -3.673367e-01       0.000000    0.000000   
50%       3.000000  117.000000   1.496408e-01      23.000000   30.500000   
75%       6.000000  140.250000   5.632228e-01      32.000000  127.250000   
max      17.000000  199.000000   2.734528e+00      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [40]:
df=pd.read_csv('Diabetes.csv')


In [42]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [45]:
minmax=MinMaxScaler()
data['BloodPressure']=minmax.fit_transform(data[['BloodPressure']])


In [46]:
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531       0.566438      20.536458   79.799479   
std       3.369578   31.972618       0.158654      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000       0.508197       0.000000    0.000000   
50%       3.000000  117.000000       0.590164      23.000000   30.500000   
75%       6.000000  140.250000       0.655738      32.000000  127.250000   
max      17.000000  199.000000       1.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [47]:
df=pd.read_csv('Diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [49]:
minmax=MinMaxScaler(feature_range=(2,5))
df['BloodPressure']=minmax.fit_transform(data[['BloodPressure']])


In [50]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531       3.699315      20.536458   79.799479   
std       3.369578   31.972618       0.475962      15.952218  115.244002   
min       0.000000    0.000000       2.000000       0.000000    0.000000   
25%       1.000000   99.000000       3.524590       0.000000    0.000000   
50%       3.000000  117.000000       3.770492      23.000000   30.500000   
75%       6.000000  140.250000       3.967213      32.000000  127.250000   
max      17.000000  199.000000       5.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [58]:
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [59]:
data=pd.read_csv('Diabetes.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [60]:
x=data[['Glucose','Age']]
y=data.Outcome

In [61]:
xtrain, xtest, ytrain, ytest=train_test_split(x, y, test_size=0.2, random_state=7)

In [66]:
scaler=StandardScaler()
xtrain_s=scaler.fit_transform(xtrain)
xtest_s=scaler.transform(xtest)


In [67]:
xtrain_s

array([[-0.370418  ,  0.01064085],
       [-0.55620696, -0.86049025],
       [ 1.17782332, -0.16358537],
       ...,
       [-1.94962414,  2.97248659],
       [-0.46331248, -1.03471647],
       [ 1.82808468,  0.27198018]])

In [69]:
xtest_s

array([[-9.27784872e-01, -7.73377136e-01],
       [ 1.89001433e+00,  1.57867683e+00],
       [ 9.92034365e-01,  8.81771950e-01],
       [-8.34890393e-01, -8.60490246e-01],
       [ 1.55984052e-01,  1.40445061e+00],
       [ 4.03702664e-01,  5.33319511e-01],
       [-3.70417997e-01, -7.73377136e-01],
       [ 5.89491622e-01, -9.47603356e-01],
       [ 1.02299919e+00,  5.33319511e-01],
       [-5.25242129e-01, -5.12037807e-01],
       [ 1.45650676e+00, -2.50698477e-01],
       [-1.11357383e+00, -6.86264026e-01],
       [ 2.13773294e+00,  3.59093291e-01],
       [ 1.58036607e+00, -5.99150917e-01],
       [ 3.21247466e-02,  2.53692104e+00],
       [-2.46558691e-01, -4.24924697e-01],
       [ 3.21247466e-02, -4.24924697e-01],
       [-3.70417997e-01, -7.64722576e-02],
       [ 4.34667490e-01, -1.03471647e+00],
       [ 2.48878531e-01,  1.92712927e+00],
       [ 9.92034365e-01, -5.12037807e-01],
       [ 6.30895730e-02, -5.99150917e-01],
       [ 1.73519020e+00,  2.18846860e+00],
       [ 2.

In [ ]:
.fit()=> it calculate mean and std
.transfrom()=> it scales the data according to mean and std
# Scaling is neded for only independent variable 
# Scaling is applied for only xtraining and xtesting
# while for scaling the testing data we use mean and std of xtraining data only.