In [22]:
# How do you compute the mean, median, and standard deviation of a NumPy array?
import numpy as np
dat=np.array([1,2,3,4,5,6])
men=np.mean(dat)
md=np.median(dat)
std=np.std(dat)
print(f"Mean of array {dat} : ",men)
print(f"Median of array {dat} : ",md)
print(f"Standard_Deviation of array {dat} : ",std)

Mean of array [1 2 3 4 5 6] :  3.5
Median of array [1 2 3 4 5 6] :  3.5
Standard_Deviation of array [1 2 3 4 5 6] :  1.707825127659933


In [49]:
#What does the axis parameter do in aggregation functions like sum() or mean()?
sum=np.sum(dat,axis=0)
print(sum)
meann=np.mean(dat,axis=0)
print(meann)

21
3.5


In [50]:
#How do you flatten a multidimensional array?
#flatten means coverting multidimensional array into 1D

In [73]:
#What is the difference between copy() and just assigning an array to another variable?
# JUST FOR ASSIGNING
y=dat

y[1]=2
print("y :",y)
print("dat :",dat)
# while just assigning it give view of original data 


# using.copy()
y=dat.copy()
y[1]=12
print("y :",y)
print("dat :",dat)
#while using .copy() we copy the orginal data now this is different array

y : [ 1  2 10  4  5  6]
dat : [ 1  2 10  4  5  6]
y : [ 1 12 10  4  5  6]
dat : [ 1  2 10  4  5  6]


In [77]:
#Explain the difference between np.array_equal() and == operator on arrays.
a = np.array([1, 2, 3])
b = np.array([1, 4, 3])

print(a == b)
#When you use == between two NumPy arrays, it compares each element one by one and returns a new array of booleans.
print(np.array_equal(a,b))
np.array_equal(a, b) # Whole Array Comparison
#This checks if both arrays are exactly equal — same shape and same values at every index.

[ True False  True]
False


In [79]:
#How do you filter an array based on a condition (e.g., values > 10)?
filter=dat[dat> 2]
print(filter)

[10  4  5  6]


In [80]:
#What is the purpose of the np.dot() function?
#  For 1D arrays → Dot Product of Vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.dot(a, b) # 1* 4+ 2* 5 + 3*6=32
print(result)


# For 2D arrays (matrices) → Matrix Multiplication
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = np.dot(A, B)
print(result)


32


In [29]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
men=np.mean(arr)
md=np.median(arr)
std=np.std(arr)
print(f"Mean of array {arr} : ",men)
print(f"Median of array {arr} : ",md)
print(f"Standard_Deviation of array {arr} : ",std)

Mean of array [[1 2 3]
 [4 5 6]
 [7 8 9]] :  5.0
Median of array [[1 2 3]
 [4 5 6]
 [7 8 9]] :  5.0
Standard_Deviation of array [[1 2 3]
 [4 5 6]
 [7 8 9]] :  2.581988897471611


In [39]:
#axis=0 fro column
#axis=1 fro row
sumc=np.sum(arr,axis=0)
print("Column_wise  sum is :" ,sumc)
sumr=np.sum(arr,axis=1)
print("Row_wise sum is :" ,sumr)

Column_wise  sum is : [12 15 18]
Row_wise sum is : [ 6 15 24]


In [42]:
#axis=0 fro column
#axis=1 fro row
menc=np.mean(arr,axis=0)
print("Column_wise  mean is :" ,menc)
menr=np.mean(arr,axis=1)
print("Row_wise mean is :" ,menr)

Column_wise  mean is : [4. 5. 6.]
Row_wise mean is : [2. 5. 8.]


In [55]:
FLAT_ARRY=arr.flatten()
print("Flatten array is : ", FLAT_ARRY)


Flatten array is :  [1 2 3 4 5 6 7 8 9]


In [ ]:
### Pandas .....

In [ ]:
#Why Pandas is a must in Data Science
for data load,clean,explore , analyze , alice/ filter

In [ ]:
#What are the two main data structures in Pandas?
#Series
# DataFrame


In [86]:
#How do you create a DataFrame from a dictionary?
import pandas as  pd
dic={
    'Name ' : ['Puja'] ,
    'Level ': ['Bachelor'],
    'Faculty' : ['ICT']}
DF=pd.DataFrame(dic)
print(DF)

  Name     Level  Faculty
0  Puja  Bachelor     ICT


In [ ]:
#How do you read a CSV file into a DataFrame?
df=pd.read_csv('filename.csv')

In [ ]:
#How do you check the shape, data types, and basic info of a DataFrame?
df.shape
df.dtypes
df.info()

In [ ]:
#How do you view the first and last few rows of a DataFrame?
df.head()
df.tail()

In [ ]:
#How do you select a single column from a DataFrame?
df.coulmnname
df['columnname']

In [ ]:
#How do you select multiple columns?
df[['column-name', 'coulmn-name',------- 'columnname']]

In [ ]:
#How do you filter rows based on a condition?
by using index loc
.loc[]

In [ ]:
#What is the difference between .loc[] and .iloc[]?
# .loc[] is used for call through label based indexing
# .iloc[]  is used for call through  position based indexing



In [ ]:
#How do you access a specific cell value in a DataFrame?
df.at[row_label , 'colun_name'] 
#Use this when you know the index label and column name.
#It’s very fast for scalar (single cell) access
df.iat[row_position, column_position]
#Use this when you want to access by number, like row 0, column 1.

In [ ]:
#How do you add a new column to a DataFrame?
df['new_column_name'] = values


In [ ]:
#How do you rename columns in a DataFrame?
df.rename(columns={'c_Name': 'column_name'}, inplace=True)

In [ ]:
#How do you drop rows or columns?
#coulmn
df.drop('column_name' , axis=1)
#rOW
df.drop(index_label, axis=0)

In [ ]:
#How do you fill or drop missing values (NaN)?
df.dropna(inplace=True)
df.fillna(value, inplace=True)

In [ ]:
#How do you change data types of columns?
df['column_name'] = df['column_name'].astype(new_type)
